(use-modules (guix channels)
             (guix inferior)
             (srfi srfi-1))

(define specs
 '("aisleriot"
   "aspell"
   "aspell-dict-en"
   "brightnessctl"
   "curl"
   "dconf"
   "dconf-editor"
   "ed"
   "emacs"
   "emacs-bash-completion"
   "emacs-company"
   "emacs-counsel-projectile"
   "emacs-diminish"
   "emacs-editorconfig"
   "emacs-elfeed"
   "emacs-elfeed-org"
   "emacs-evil"
   "emacs-evil-collection"
   "emacs-evil-commentary"
   "emacs-evil-magit"
   "emacs-evil-matchit"
   "emacs-evil-org"
   "emacs-evil-surround"
   "emacs-flycheck"
   "emacs-geiser"
   "emacs-general"
   "emacs-go-mode"
   "emacs-guix"
   "emacs-haskell-mode"
   "emacs-helpful"
   "emacs-ivy"
   "emacs-ledger-mode"
   "emacs-magit"
   "emacs-markdown-mode"
   "emacs-mixed-pitch"
   "emacs-mu4e-conversation"
   "emacs-nov-el"
   "emacs-org"
   "emacs-org-bullets"
   "emacs-pass"
   "emacs-projectile"
   "emacs-rainbow-mode"
   "emacs-restart-emacs"
   "emacs-slack"
   "emacs-smart-mode-line"
   "emacs-smartparens"
   "emacs-use-package"
   "emacs-vimrc-mode"
   "emacs-which-key"
   "emacs-ws-butler"
   "emacs-yasnippet"
   "emacs-yasnippet-snippets"
   "feh"
   "ffmpeg"
   "file"
   "font-go"
   "font-google-noto"
   "ghc-xmonad-contrib"
   "git"
   "glibc-utf8-locales"
   "gnome-mines"
   "gnome-sudoku"
   "gnome-tweaks"
   "gnupg"
   "gst-plugins-bad"
   "gst-plugins-ugly"
   "guile"
   "icecat"
   "ikiwiki"
   "imagemagick"
   "isync"
   "ledger"
   "libnotify"
   "libreoffice"
   "mcron"
   "moreutils"
   "mpd"
   "mpd-mpc"
   "mpv"
   "msmtp"
   "mu"
   "mutt"
   "ncmpc"
   "neovim"
   "nss-certs"
   "openssh"
   "pass-otp"
   "password-store"
   "pinentry"
   "poppler"
   "rclone"
   "recutils"
   "redshift"
   "reptyr"
   "restic"
   "rsync"
   "shellcheck"
   "shepherd"
   "stow"
   "syncthing"
   "the-silver-searcher"
   "tmux"
   "transmission:gui"
   "trash-cli"
   "ungoogled-chromium"
   "vcsh"
   "vim"
   "w3m"
   "xclip"
   "xdg-utils"
   "xdotool"
   "xmonad"
   "xrdb"
   "xterm"
   "youtube-dl"
   "zathura"
   "zathura-djvu"
   "zathura-pdf-mupdf"
   "zathura-ps"))

(define inferior
  (inferior-for-channels
   (list (channel (name 'guix)
                  (url "file:///home/ajgrf/src/guix")
                  (branch "pulseaudio-dlna")))))

(packages->manifest
 (cons*
  (first (lookup-inferior-packages inferior "pulseaudio-dlna"))
  (map (compose list specification->package+output) specs)))
