local lexers = vis.lexers

lexers.STYLE_DEFAULT = 'fore:default,back:default'
lexers.STYLE_NOTHING = ''
lexers.STYLE_CLASS = lexers.STYLE_DEFAULT
lexers.STYLE_COMMENT = 'fore:yellow,italics'
lexers.STYLE_CONSTANT = lexers.STYLE_DEFAULT
lexers.STYLE_DEFINITION = 'fore:blue,bold'
lexers.STYLE_ERROR = 'fore:red,italics'
lexers.STYLE_FUNCTION = lexers.STYLE_DEFAULT
lexers.STYLE_KEYWORD = lexers.STYLE_DEFAULT
lexers.STYLE_LABEL = lexers.STYLE_DEFAULT
lexers.STYLE_NUMBER = lexers.STYLE_DEFAULT
lexers.STYLE_OPERATOR = lexers.STYLE_DEFAULT
lexers.STYLE_REGEX = 'fore:green'
lexers.STYLE_STRING = 'fore:green'
lexers.STYLE_PREPROCESSOR = lexers.STYLE_DEFAULT
lexers.STYLE_TAG = lexers.STYLE_DEFAULT
lexers.STYLE_TYPE = lexers.STYLE_DEFAULT
lexers.STYLE_VARIABLE = lexers.STYLE_DEFAULT
lexers.STYLE_WHITESPACE = ''
lexers.STYLE_EMBEDDED = 'fore:magenta'
lexers.STYLE_IDENTIFIER = lexers.STYLE_DEFAULT

lexers.STYLE_LINENUMBER = 'fore:black,back:8'
lexers.STYLE_LINENUMBER_CURSOR = lexers.STYLE_LINENUMBER
lexers.STYLE_CURSOR = 'reverse'
lexers.STYLE_CURSOR_PRIMARY = lexers.STYLE_CURSOR..',fore:magenta'
lexers.STYLE_CURSOR_LINE = 'back:white'
lexers.STYLE_COLOR_COLUMN = 'back:white'
lexers.STYLE_SELECTION = 'back:11'
lexers.STYLE_STATUS = 'fore:black,back:8'
lexers.STYLE_STATUS_FOCUSED = 'fore:15,back:blue,bold'
lexers.STYLE_SEPARATOR = lexers.STYLE_DEFAULT
lexers.STYLE_INFO = 'fore:default,back:default,bold'
lexers.STYLE_EOF = ''
