directory: /media/ajgrf/ajgdepot/Music
ui:
    color: no
original_date: yes
sort_album: albumartist+ album+
max_filename_length: 140
paths:
    default: $albumartist_sort/$album%aunique{}/$track $title
    singleton: Non-Album/$artist_sort/$title
    albumtype:soundtrack: Soundtracks/$album%aunique{}/$track $title
    comp: Compilations/$album%aunique{}/$track $title
per_disc_numbering: no
import:
    move: yes
    languages: []
    # languages: ['zho', 'zh_TW', 'zh_CN', 'en_US', 'en']
match:
    preferred:
        countries: ['US']
        media: ['CD', 'Digital Media|File']
        original_year: yes
plugins: chroma convert embedart fetchart info lastgenre lyrics replaygain scrub
chroma:
    auto: no
embedart:
    auto: no
replaygain:
    backend: gstreamer
convert:
    format: opus
    dest: ~/Music
    embed: no
    copy_album_art: yes
    max_bitrate: 160
